<?php

return array (
  'AF-BDS' => 'Badakhshan',
  'AF-BGL' => 'Baghlan',
  'AF-BAL' => 'Balkh',
  'AF-BAM' => 'Bamyan',
  'AF-DAY' => 'Daykundi',
  'AF-FRA' => 'Farah',
  'AF-FYB' => 'Faryab',
  'AF-GHA' => 'Ghazni',
  'AF-GHO' => 'Ghor',
  'AF-HEL' => 'Helmand',
  'AF-HER' => 'Herat',
  'AF-JOW' => 'Jowzjan',
  'AF-KAB' => 'Kabul',
  'AF-KAN' => 'Kandahar',
  'AF-KAP' => 'Kapisa',
  'AF-KHO' => 'Khost',
  'AF-KNR' => 'Kunar',
  'AF-KDZ' => 'Kunduz',
  'AF-LAG' => 'Laghman',
  'AF-LOG' => 'Logar',
  'AF-NAN' => 'Nangarhar',
  'AF-NIM' => 'Nimroz',
  'AF-NUR' => 'Nuristan',
  'AF-PKA' => 'Paktia',
  'AF-PKT' => 'Paktika',
  'AF-PAN' => 'Panjshir',
  'AF-PAR' => 'Parwan',
  'AF-SAM' => 'Samangan',
  'AF-SAR' => 'Sar-e Pol',
  'AF-TAK' => 'Takhar',
  'AF-URU' => 'Urozgan',
  'AF-WAR' => 'Wardak',
  'AF-ZAB' => 'Zabul',
);
