<?php

return array (
  'CD-KN' => 'Kinshasa',
  'CD-BC' => 'Kongo Central',
  'CD-KG' => 'Kwango',
  'CD-KW' => 'Kwilu',
  'CD-MA' => 'Mai-Ndombe',
  'CD-EQ' => 'Équateur',
  'CD-MO' => 'Mongala',
  'CD-NU' => 'Nord-Ubangi',
  'CD-SU' => 'Sud-Ubangi',
  'CD-TU' => 'Tshuapa',
  'CD-IT' => 'Ituri',
  'CD-HU' => 'Haut-Uele',
  'CD-BA' => 'Bas-Uele',
  'CD-TO' => 'Tshopo',
  'CD-NK' => 'Nord-Kivu',
  'CD-SK' => 'Sud-Kivu',
  'CD-MN' => 'Maniema',
  'CD-HL' => 'Haut-Lomami',
  'CD-LU' => 'Lualaba',
  'CD-HK' => 'Haut-Katanga',
  'CD-TA' => 'Tanganyika',
  'CD-LO' => 'Lomami',
  'CD-SA' => 'Sankuru',
  'CD-KC' => 'Kasaï-Central',
  'CD-KS' => 'Kasaï',
  'CD-KO' => 'Kasaï-Oriental',
);
