<?php

return array (
  'GB-ENG' => 'England',
  'GB-SCT' => 'Scotland',
  'GB-WLS' => 'Wales',
  'GB-NIR' => 'Northern Ireland',
  'GB-BDS' => 'Bedfordshire',
  'GB-BKM' => 'Buckinghamshire',
  'GB-CAM' => 'Cambridgeshire',
  'GB-CHS' => 'Cheshire',
  'GB-CON' => 'Cornwall',
  'GB-CMA' => 'Cumbria',
  'GB-DBY' => 'Derbyshire',
  'GB-DEV' => 'Devon',
  'GB-DOR' => 'Dorset',
  'GB-DUR' => 'Durham',
  'GB-ESX' => 'Essex',
  'GB-GLS' => 'Gloucestershire',
  'GB-HAM' => 'Hampshire',
  'GB-HRT' => 'Hertfordshire',
  'GB-KEN' => 'Kent',
  'GB-LAN' => 'Lancashire',
  'GB-LEI' => 'Leicestershire',
  'GB-LIN' => 'Lincolnshire',
  'GB-NFK' => 'Norfolk',
  'GB-NYK' => 'North Yorkshire',
  'GB-NTH' => 'Northamptonshire',
  'GB-NTT' => 'Nottinghamshire',
  'GB-OXF' => 'Oxfordshire',
  'GB-SOM' => 'Somerset',
  'GB-STS' => 'Staffordshire',
  'GB-SFK' => 'Suffolk',
  'GB-SRY' => 'Surrey',
  'GB-WAR' => 'Warwickshire',
  'GB-WSX' => 'West Sussex',
  'GB-WOR' => 'Worcestershire',
);
