<?php

return array (
  'KH-12' => 'Phnom Penh',
  'KH-01' => 'Banteay Meanchey',
  'KH-02' => 'Battambang',
  'KH-03' => 'Kampong Cham',
  'KH-04' => 'Kampong Chhnang',
  'KH-05' => 'Kampong Speu',
  'KH-06' => 'Kampong Thom',
  'KH-07' => 'Kampot',
  'KH-08' => 'Kandal',
  'KH-09' => 'Koh Kong',
  'KH-10' => 'Kratie',
  'KH-11' => 'Mondulkiri',
  'KH-22' => 'Oddar Meanchey',
  'KH-13' => 'Preah Vihear',
  'KH-14' => 'Prey Veng',
  'KH-15' => 'Pursat',
  'KH-16' => 'Ratanakiri',
  'KH-17' => 'Siem Reap',
  'KH-18' => 'Sihanoukville',
  'KH-19' => 'Stung Treng',
  'KH-20' => 'Svay Rieng',
  'KH-21' => 'Takeo',
  'KH-23' => 'Kep',
  'KH-24' => 'Pailin',
  'KH-25' => 'Tboung Khmum',
);
