<?php

return array (
  'LV-001' => 'Aglonas novads',
  'LV-002' => 'Aizkraukles novads',
  'LV-003' => 'Aizputes novads',
  'LV-004' => 'Aknīstes novads',
  'LV-005' => 'Alojas novads',
  'LV-006' => 'Alsungas novads',
  'LV-007' => 'Alūksnes novads',
  'LV-008' => 'Amatas novads',
  'LV-009' => 'Apes novads',
  'LV-010' => 'Auces novads',
  'LV-011' => 'Ādažu novads',
  'LV-012' => 'Babītes novads',
  'LV-013' => 'Baldones novads',
  'LV-014' => 'Baltinavas novads',
  'LV-015' => 'Balvu novads',
  'LV-016' => 'Bauskas novads',
  'LV-017' => 'Beverīnas novads',
  'LV-018' => 'Brocēnu novads',
  'LV-019' => 'Burtnieku novads',
  'LV-020' => 'Carnikavas novads',
  'LV-021' => 'Cēsu novads',
  'LV-022' => 'Cesvaines novads',
  'LV-023' => 'Ciblas novads',
  'LV-024' => 'Dagdas novads',
  'LV-025' => 'Daugavpils novads',
  'LV-026' => 'Dobeles novads',
  'LV-027' => 'Dundagas novads',
  'LV-028' => 'Durbes novads',
  'LV-029' => 'Engures novads',
  'LV-030' => 'Ērgļu novads',
  'LV-RIX' => 'Rīga',
  'LV-DGP' => 'Daugavpils',
  'LV-JEL' => 'Jelgava',
  'LV-JUR' => 'Jūrmala',
  'LV-LPX' => 'Liepāja',
  'LV-REZ' => 'Rēzekne',
  'LV-VEN' => 'Ventspils',
);
