<?php

return array (
  'VN-01' => 'Hanoi',
  'VN-79' => 'Ho Chi Minh City',
  'VN-48' => 'Da Nang',
  'VN-31' => 'Hai Phong',
  'VN-92' => 'Can Tho',
  'VN-40' => 'Nghe An',
  'VN-44' => 'Quang Binh',
  'VN-45' => 'Quang Tri',
  'VN-46' => 'Thua Thien Hue',
  'VN-49' => 'Quang Nam',
  'VN-51' => 'Quang Ngai',
  'VN-52' => 'Binh Dinh',
  'VN-54' => 'Phu Yen',
  'VN-56' => 'Khanh Hoa',
  'VN-58' => 'Ninh Thuan',
  'VN-60' => 'Binh Thuan',
  'VN-62' => 'Kon Tum',
  'VN-64' => 'Gia Lai',
  'VN-66' => 'Dak Lak',
  'VN-67' => 'Dak Nong',
  'VN-68' => 'Lam Dong',
  'VN-70' => 'Binh Phuoc',
  'VN-72' => 'Tay Ninh',
  'VN-74' => 'Binh Duong',
  'VN-75' => 'Dong Nai',
  'VN-77' => 'Ba Ria - Vung Tau',
  'VN-80' => 'Long An',
  'VN-82' => 'Tien Giang',
  'VN-83' => 'Ben Tre',
  'VN-84' => 'Tra Vinh',
  'VN-86' => 'Vinh Long',
  'VN-87' => 'Dong Thap',
  'VN-89' => 'An Giang',
  'VN-91' => 'Kien Giang',
  'VN-93' => 'Hau Giang',
  'VN-94' => 'Soc Trang',
  'VN-95' => 'Bac Lieu',
  'VN-96' => 'Ca Mau',
);
